// mutation 常量

export const SET_MPVUEINFO = 'SET_MPVUEINFO';
export const SET_CHECKITEM = 'SET_CHECKITEM';
export const SET_CHECKCOOKINGTYPE = 'SET_CHECKCOOKINGTYPE';
export const SET_LISTDATA = 'SET_LISTDATA';
export const SET_LISTRANDOMDATA = 'SET_LISTRANDOMDATA';
